version: '3.9'

services:
  dash:
    command: python3 main.py
    image: shaficse/ml-ait-st124047:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80