name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build_n_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Compose services
        run: docker-compose -f docker-compose.yml pull

      # Add the "Build and Push" step here
      - name: Build and push Docker images
        run: |
         docker build -t shaficse/shaficse/checksalary:latest .
         docker push     shaficse/shaficse/checksalary:latest

      - name: Up Docker Compose services
        run: docker-compose -f docker-compose.yml up -d

  ##uncomment this part if you want to deploy
  # deploy:
  #   needs: build_n_push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: SSH Remote Commands
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ vars.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.KEY }}
  #         proxy_host: ${{ vars.PROXY_HOST }}
  #         proxy_username: ${{ secrets.USERNAME }}
  #         proxy_key: ${{ secrets.KEY }}
  #         script: |
  #           tag=$github_ref_name docker compose -f st124047/docker-compose.yaml down
  #           tag=$github_ref_name docker compose -f st124047/docker-compose.yaml up -d
        
