name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install numpy scikit-learn pytest

      - name: Run unit tests
        run: |
          pytest --verbose app/test.py

  build_n_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Compose services
        run: docker-compose -f docker-compose.yml pull

      # Add the "Build and Push" step here
      - name: Build and push Docker images
        run: |
         docker build -t shaficse/checksalary:latest .
         docker push     shaficse/checksalary:latest

      - name: Up Docker Compose services
        run: docker-compose -f docker-compose.yml up -d