name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install -r requirements.txt

      - name: Run unit tests
        run: pytest --verbose tests

  build_n_push:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t shaficse/checksalary:v1 .
          docker push shaficse/checksalary:v1
